version: '3.3'
services:
  wikigame:
    build: .
    ports: ["5033:5000"]
    restart: "unless-stopped"
    volumes:
      - ./persistance:/persistance
      - ./data:/data
      - ./wikigame/static:/app/wikigame/static